
import java.awt.Button;
import java.awt.TextField;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author drmas
 */
public class NewFrame extends javax.swing.JFrame {
    
    private final QuestionBank mQuestionLibarary = new QuestionBank();
    private String mAnswer;
    private int mScore = 0;
    private int mQuestionNumber = 0;

    /**
     * Creates new form NewFrame
     */
    public NewFrame() {
        initComponents();
    }

    //TextField mScoreView = (TextField) new TextField();
    //TextField mQuestionview = (TextField) new TextField();
    //JButton mButtonChoice1 = (JButton) new JButton();
   // JButton mButtonChoice2 = (JButton) new JButton(); 
   // JButton mButtonChoice3 = (JButton) new JButton(); 

    private void updateQuestion(){
         if (mQuestionNumber < mQuestionLibarary.getLength()){
            mQuestionview.setText(mQuestionLibarary.getQuestions(mQuestionNumber));
            mButtonChoice1.setText(mQuestionLibarary.getQuestions(mQuestionNumber, 1));
            mButtonChoice2.setText(mQuestionLibarary.getQuestions(mQuestionNumber, 2));
            mButtonChoice3.setText(mQuestionLibarary.getQuestions(mQuestionNumber, 3));
            mAnswer = mQuestionLibarary.getCorrectAnswer(mQuestionNumber);
            mQuestionNumber++;
         } else {
             JOptionPane.showMessageDialog(null, "It Was The Last Question!");
         }
    }
    private void updateScore(int point){
       mScoreView.setText("" + mScore+"/"+mQuestionLibarary.getLength()); 
    }

    public void onClickbtn(JButton answer){
        if(answer.getText().equals(mAnswer)){
            mScore = mScore + 1;
            JOptionPane.showMessageDialog(null, "Correct");
        } else {
            JOptionPane.showMessageDialog(null, "Rwong");
        }
        updateScore(mScore);
        updateQuestion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        mScoreView = new javax.swing.JTextField();
        mQuestionview = new javax.swing.JTextField();
        mButtonChoice1 = new javax.swing.JButton();
        mButtonChoice2 = new javax.swing.JButton();
        mButtonChoice3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mScoreView.setText("Score");

        mQuestionview.setText("Question");

        mButtonChoice1.setText("jButton1");
        mButtonChoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonChoice1ActionPerformed(evt);
            }
        });

        mButtonChoice2.setText("jButton2");
        mButtonChoice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonChoice2ActionPerformed(evt);
            }
        });

        mButtonChoice3.setText("jButton3");
        mButtonChoice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonChoice3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mButtonChoice1)
                        .addGap(78, 78, 78)
                        .addComponent(mScoreView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(mButtonChoice3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mButtonChoice2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mQuestionview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(mScoreView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mButtonChoice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mQuestionview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mButtonChoice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mButtonChoice3)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mButtonChoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonChoice1ActionPerformed

    }//GEN-LAST:event_mButtonChoice1ActionPerformed

    private void mButtonChoice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonChoice2ActionPerformed

    }//GEN-LAST:event_mButtonChoice2ActionPerformed

    private void mButtonChoice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonChoice3ActionPerformed

    }//GEN-LAST:event_mButtonChoice3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton mButtonChoice1;
    private javax.swing.JButton mButtonChoice2;
    private javax.swing.JButton mButtonChoice3;
    private javax.swing.JTextField mQuestionview;
    private javax.swing.JTextField mScoreView;
    // End of variables declaration//GEN-END:variables

    private void onClickbtn(String mAnswer) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
